# Generated by Django 2.1.2 on 2018-11-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robocop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('values', models.CharField(max_length=1023)),
                ('image', models.CharField(max_length=255)),
                ('flag', models.CharField(max_length=10)),
            ],
        ),
    ]
